name: GitHub Actions Demo

on: [push]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

  build_backend:
    needs: [setup]
    name: Build backend
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - run: cd backend && ./gradlew build

  build_frontend:
    needs: [setup]
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - run: cd backend && ./gradlew generateApiSpecsFrontend

  # viola:
  #   name: Viola
  #   needs: [checkout]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: List files in the repository
  #       run: |
  #         ls ${{ github.workspace }}
  #     - run: echo "🍏 This job's status is ${{ job.status }}."

  # zoom:
  #   name: Zoom
  #   needs: [checkout]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: List files in the repository
  #       run: |
  #         ls ${{ github.workspace }}
  #     - run: echo "🍏 This job's status is ${{ job.status }}."